import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../node_modules/@fortawesome/fontawesome-free/css/all.min.css";
import "./globals.css";
import UserContextProvider from './Context/UserContext'
import Navbar from './_mainlayout/_navbar/page'
import Footer from './_mainlayout/_footer/page'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <UserContextProvider>
          <Navbar />
          {children}
          <Footer />
        </UserContextProvider>
      </body>
    </html>
  )
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "../../node_modules/@fortawesome/fontawesome-free/css/all.min.css";
// import "./globals.css";
// import Footer from "./_mainlayout/_footer/page";
// import Navbar from "./_mainlayout/_navbar/page";
// import UserContextProvider from "./Context/UserContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className="">
//         <UserContextProvider>
//           <Navbar />
//           {children}
//           <Footer />
//         </UserContextProvider>
//       </body>
//     </html>
//   );
// }

// // className={`${geistSans.variable} ${geistMono.variable} antialiased`}